volumes:
  db_data:
  app_logs:

services:
  db:
    container_name: db
    image: postgres:14.9-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./sql:/docker-entrypoint-initdb.d
    ports:
      - $DB_PORT:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USER -d $DB_NAME']
      interval: 10s
      timeout: 5s
      retries: 5
    # networks:
    #   - network_name

  app:
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: dockerfile
      args:
        APP_ENV: development
    volumes:
      - ./src:/app/src
      - app_logs:/app/logs
    ports:
      - $APP_PORT:8080
    # networks:
    #   - network_name
