"""empty message

Revision ID: 559d6cb9eb94
Revises: 92d4c3f3c74c
Create Date: 2024-09-21 21:32:27.231915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559d6cb9eb94'
down_revision: Union[str, None] = '92d4c3f3c74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_links', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_links', 'name')
    # ### end Alembic commands ###
