"""empty message

Revision ID: 512334f02076
Revises: 8ef452f2d358
Create Date: 2024-08-25 22:44:57.155682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512334f02076'
down_revision: Union[str, None] = '8ef452f2d358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsing_results', 'commission_percent',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('parsing_results', 'deposit_percent',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsing_results', 'deposit_percent',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('parsing_results', 'commission_percent',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
