"""empty message

Revision ID: 42d879243f9f
Revises: c631d36cfe4a
Create Date: 2024-09-24 20:52:49.829257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c631d36cfe4a'
down_revision: Union[str, None] = '559d6cb9eb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_telegrams',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_telegrams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk_users_telegrams'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_telegrams')
    # ### end Alembic commands ###
