"""empty message

Revision ID: 182882c03b8a
Revises: 512334f02076
Create Date: 2024-08-26 19:46:32.133763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182882c03b8a'
down_revision: Union[str, None] = '512334f02076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_links', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_links', 'is_active')
    # ### end Alembic commands ###
