"""empty message

Revision ID: 8ef452f2d358
Revises: bb9d4ae0b3cd
Create Date: 2024-08-25 21:17:57.114856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef452f2d358'
down_revision: Union[str, None] = 'bb9d4ae0b3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsing_results', 'flat_area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsing_results', 'flat_area',
               existing_type=sa.String(length=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
